version: '3.2'

services:
  pvw:
    image: public.ecr.aws/h3lioviz/paraview_web_repo:${PVW_IMAGE_TAG:-h3lioviz-egl}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
