name: Upload backend release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to s3
      # ${GITHUB_REF#refs/*/} will resolve "/refs/tags/v1.0.1" to "v1.0.1"
      run: |
        aws s3 cp --recursive . s3://enlil-data/server-code/${GITHUB_REF#refs/*/}/ --exclude="*.git/*"
